name: Cleanup Docker Host

on:
  push:
    branches:
      - "master"
  schedule:
    - cron: '10 22 * * *'

jobs:
  cleanup:
    runs-on: self-hosted

    steps:
      - name: 'Cleanup docker host'
        run: |
          docker image prune -f
