name: Cleanup Docker Host

on:
  schedule:
    - cron: '10 22 * * *'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: 'Cleanup docker host'
        run: |
          docker image prune -f

      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
