name: Cleanup Docker Host

on:
  push:
    branches:
      - "master"
  schedule:
    - cron: '10 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Cleanup docker host'
        run: |
          docker image prune -f

      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
