name: Build Docker image for Github

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: "Cleanup build folder"
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          check-latest: true

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Github Registry
        id: gh-registry
        run: |
          echo "GITHUB_REGISTRY=ghcr.io" >> $GITHUB_ENV

      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            secret/deployments/github registry | REGISTRY;
            secret/deployments/github token | GH_TOKEN

      - name: Import Secrets for Staging
        id: import-secrets-staging
        uses: hashicorp/vault-action@v3
        if: (github.event.inputs.environment != 'production' && startsWith(github.event.ref, 'refs/heads/master')) || github.event.inputs.environment == 'staging'
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            staging/mgmt/hetzner deployment_bucket_access_key | BUCKET_ACCESS_KEY;
            staging/mgmt/hetzner deployment_bucket_endpoint | BUCKET_ENDPOINT;
            staging/mgmt/hetzner deployment_bucket_name | BUCKET_NAME;
            staging/mgmt/hetzner deployment_bucket_region | BUCKET_REGION;
            staging/mgmt/hetzner deployment_bucket_secret_key | BUCKET_SECRET_KEY

      - name: Import Secrets for Production
        id: import-secrets-production
        uses: hashicorp/vault-action@v3
        if: startsWith(github.event.ref, 'refs/tags/v') || github.event.inputs.environment == 'production'
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            secret/mgmt/hetzner deployment_bucket_access_key | BUCKET_ACCESS_KEY;
            secret/mgmt/hetzner deployment_bucket_endpoint | BUCKET_ENDPOINT;
            secret/mgmt/hetzner deployment_bucket_name | BUCKET_NAME;
            secret/mgmt/hetzner deployment_bucket_region | BUCKET_REGION;
            secret/mgmt/hetzner deployment_bucket_secret_key | BUCKET_SECRET_KEY

      - name: Extract staging metadata for Docker on Github
        id: meta_staging
        uses: docker/metadata-action@v5
        if: (github.event.inputs.environment != 'production' && startsWith(github.event.ref, 'refs/heads/master')) || github.event.inputs.environment == 'staging'
        with:
          images: ${{ env.GITHUB_REGISTRY }}/${{ github.repository }}
          tags: |
            type=schedule
            type=semver,pattern={{version}}
            type=raw,value=latest,enable=${{ inputs.environment == 'staging' || github.event.ref == format('refs/heads/{0}', 'master') }}

      - name: Extract production metadata for Docker
        id: meta_live
        uses: docker/metadata-action@v5
        if: startsWith(github.event.ref, 'refs/tags/v') || github.event.inputs.environment == 'production'
        with:
          images: ${{ env.GITHUB_REGISTRY }}/${{ github.repository }}
          tags: |
            type=schedule
            type=semver,pattern={{version}}
            type=raw,value=stable,enable=${{ inputs.environment == 'production' || github.event.ref == format('refs/heads/{0}', 'master') }}

      - name: Extract branch name
        shell: bash
        run: |
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
          echo "tag=$(git describe --tags || git rev-parse --short HEAD || echo 'none')" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: "Get version"
        run: |
          echo "${{ steps.extract_branch.outputs.branch }}" > version.txt

      - name: Build and push to staging
        id: push
        uses: docker/build-push-action@v5
        if: (github.event.inputs.environment != 'production' && startsWith(github.event.ref, 'refs/heads/master')) || github.event.inputs.environment == 'staging'
        with:
          file: Dockerfile
          context: .
          build-args: |
            VAULT_ADDR=${{ secrets.VAULT_ADDR }}
            VAULT_ROLE_ID=${{ secrets.VAULT_ROLE_ID }}
            VAULT_SECRET_ID=${{ secrets.VAULT_SECRET_ID }}
            GH_TOKEN=${{ env.GH_TOKEN }}
          push: true
          tags: |
            ${{ steps.meta_staging.outputs.tags }}

      - name: Build and push to production
        uses: docker/build-push-action@v5
        if: startsWith(github.event.ref, 'refs/tags/v') || github.event.inputs.environment == 'production'
        with:
          file: Dockerfile
          context: .
          build-args: |
            VAULT_ADDR=${{ secrets.VAULT_ADDR }}
            VAULT_ROLE_ID=${{ secrets.VAULT_ROLE_ID }}
            VAULT_SECRET_ID=${{ secrets.VAULT_SECRET_ID }}
            GH_TOKEN=${{ env.GH_TOKEN }}
          push: true
          tags: |
            ${{ steps.meta_live.outputs.tags }}

      - name: Set up S3cmd for staging
        uses: mthie/s3cmd@main
        if: (github.event.inputs.environment != 'production' && startsWith(github.event.ref, 'refs/heads/master')) || github.event.inputs.environment == 'staging'
        with:
          provider: hcloud
          region: ${{ steps.import-secrets-staging.outputs.BUCKET_REGION }}
          access_key: ${{ steps.import-secrets-staging.outputs.BUCKET_ACCESS_KEY }}
          secret_key: ${{ steps.import-secrets-staging.outputs.BUCKET_SECRET_KEY }}

      - name: "Upload version files for staging"
        if: (github.event.inputs.environment != 'production' && startsWith(github.event.ref, 'refs/heads/master')) || github.event.inputs.environment == 'staging'
        run: |
          cp version.txt ${{ steps.extract_branch.outputs.tag }}.txt
          s3cmd rm s3://${{ env.BUCKET_NAME }}/contentflow-builds/${{ github.event.repository.name }}/*.txt || true
          s3cmd put ${{ steps.extract_branch.outputs.tag }}.txt s3://${{ env.BUCKET_NAME }}/contentflow-builds/${{ github.event.repository.name }}/

      - name: Set up S3cmd for production
        uses: mthie/s3cmd@main
        if: startsWith(github.event.ref, 'refs/tags/v') || github.event.inputs.environment == 'production'
        with:
          provider: hcloud
          region: ${{ steps.import-secrets-production.outputs.BUCKET_REGION }}
          access_key: ${{ steps.import-secrets-production.outputs.BUCKET_ACCESS_KEY }}
          secret_key: ${{ steps.import-secrets-production.outputs.BUCKET_SECRET_KEY }}

      - name: "Upload version files for production"
        run: |
          cp version.txt ${{ steps.extract_branch.outputs.tag }}.txt
          s3cmd rm s3://${{ env.BUCKET_NAME }}/contentflow-builds/${{ github.event.repository.name }}/*.txt || true
          s3cmd put ${{ steps.extract_branch.outputs.tag }}.txt s3://${{ env.BUCKET_NAME }}/contentflow-builds/${{ github.event.repository.name }}/
