name: Build Docker image

on:
  workflow_call:

jobs:
  build:
    runs-on: self-hosted

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          check-latest: true

      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            secret/deployments/gcr secret_file | SERVICE_ACCOUNT_KEY;
            secret/deployments/github registry | REGISTRY;
            secret/deployments/github token | GH_TOKEN

      - name: Extract live metadata for Docker
        id: meta_live
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/contentflow-2/production/${{ github.event.repository.name }}
          tags: |
            type=schedule
            type=semver,pattern={{version}}
            type=raw,value=latest,enable=${{ github.event.ref == format('refs/heads/{0}', 'master') }}

      - name: Extract staging metadata for Docker
        id: meta_staging
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/contentflow-2/staging/${{ github.event.repository.name }}
          tags: |
            type=schedule
            type=semver,pattern={{version}}
            type=raw,value=latest,enable=${{ github.event.ref == format('refs/heads/{0}', 'master') }}

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ env.SERVICE_ACCOUNT_KEY }}'

      - name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@v2

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: Extract branch name
        shell: bash
        run: |
          echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
          echo "tag=$(git describe --tags || git rev-parse --short HEAD || echo 'none')" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: "Get version"
        run: |
          echo "${{ steps.extract_branch.outputs.branch }}" > version.txt

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGISTRY }} --quiet

      - name: Build and push to staging
        uses: docker/build-push-action@v5
        if: startsWith(github.event.ref, 'refs/heads/master')
        with:
          file: Dockerfile
          context: .
          build-args: |
            VAULT_ADDR=${{ secrets.VAULT_ADDR }}
            VAULT_ROLE_ID=${{ secrets.VAULT_ROLE_ID }}
            VAULT_SECRET_ID=${{ secrets.VAULT_SECRET_ID }}
            GH_TOKEN=${{ env.GH_TOKEN }}
          push: true
          tags: |
            ${{ steps.meta_staging.outputs.tags }}

      - name: "set version for staging"
        if: startswith(github.event.ref, 'refs/heads/master')
        run: |
          cp version.txt ${{ steps.extract_branch.outputs.tag }}
          gsutil rm gs://contentflow-builds/contentflow/${{ github.event.repository.name }}/staging/* || true
      - name: 'Upload staging version file'
        if: startsWith(github.event.ref, 'refs/heads/master')
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: ${{ steps.extract_branch.outputs.tag }}
          headers: |-
            content-type: text/plain
          destination: "contentflow-builds/contentflow/${{ github.event.repository.name }}/staging/"

      - name: Build and push to production
        uses: docker/build-push-action@v5
        if: startsWith(github.event.ref, 'refs/tags/v')
        with:
          file: Dockerfile
          context: .
          push: true
          tags: |
            ${{ steps.meta_live.outputs.tags }}

      - name: "set version for production"
        if: startswith(github.event.ref, 'refs/tags/v')
        run: |
          cp version.txt ${{ steps.extract_branch.outputs.tag }}
          gsutil rm gs://contentflow-builds/contentflow/${{ github.event.repository.name }}/production/* || true

      - name: 'Upload production version file'
        if: startsWith(github.event.ref, 'refs/tags/v')
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: ${{ steps.extract_branch.outputs.tag }}
          headers: |-
            content-type: text/plain
          destination: "contentflow-builds/contentflow/${{ github.event.repository.name }}/production/"
